fix(release.yml): manually exclude two files from Git diff check due to known Pulumi codegen bug

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -98,19 +98,21 @@ jobs:
       - name: Build SDK
         run: make build_${{ matrix.language }}
 
-      # Skip checking that the Git worktree is clean for now since the `make tfgen` and `make build_sdks` commands produce small
-      # Git diffs due to a bug in the Pulumi code generation process where the custom package name is not being used:
+      # Usually there are no Git diffs produced in the pipeline, however there are currently two files manually excluded
+      # (see below) since the `make tfgen` and `make build_sdks` commands both produce small Git diffs due to a bug in the
+      # Pulumi code generation process where the custom package name is not being used:
       # https://github.com/pulumi/pulumi/issues/15979
-      #
-      # - name: Check worktree clean
-      #   run: |
-      #     git update-index -q --refresh
-      #     if ! git diff-files --quiet; then
-      #         >&2 echo "error: working tree is not clean, aborting!"
-      #         git status
-      #         git diff
-      #         exit 1
-      #     fi
+      - name: Check worktree clean
+        run: |
+          git update-index -q --refresh
+          if ! git diff-files --quiet \
+            ':(exclude)provider/cmd/pulumi-resource-onepassword/schema.json' \
+            ':(exclude)sdk/nodejs/getItem.ts'; then
+              >&2 echo "error: working tree is not clean, aborting!"
+              git status
+              git diff
+              exit 1
+          fi
 
       - if: ${{ matrix.language == 'python' && env.PUBLISH_PYPI == 'true' }}
         name: Publish package to PyPI
